services:
  frontend:
    image: ghcr.io/afandi-fa/imp/frontend:latest
    container_name: imp-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    image: ghcr.io/afandi-fa/imp/backend:latest
    container_name: imp-backend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network: