services:
  frontend:
    image: ghcr.io/afandi-fa/imp/frontend:latest
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: ghcr.io/afandi-fa/imp/backend:latest
    restart: unless-stopped
    env_file: .env
    expose:
      - "3001"