FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@10.29.3 --activate
WORKDIR /app

FROM base AS builder
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY shared/package.json ./shared/
COPY backend/package.json ./backend/
RUN pnpm install --frozen-lockfile
COPY shared ./shared
COPY backend ./backend
RUN pnpm --filter @imp/backend build

FROM node:22-alpine AS runner
RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

WORKDIR /app
ENV NODE_ENV=production

# copy dependency context
COPY --from=builder /app/pnpm-lock.yaml ./
COPY --from=builder /app/package.json ./
COPY --from=builder /app/backend/package.json ./backend/package.json
COPY --from=builder /app/shared/package.json ./shared/package.json

# install hanya backend deps
RUN pnpm install --prod --filter @imp/backend

# copy hasil build
COPY --from=builder /app/backend/dist ./dist
COPY --from=builder /app/backend/src/db/migrations ./migrations

EXPOSE 3001
CMD ["node", "dist/index.js"]